// stages.js — chapter configs + authored spawn timelines.
//
// Each stage is plain data: visual theme, scroll speed, duration, and a
// time-ordered list of spawns. Objects appear off the right edge at the given
// time (seconds into the stage) and scroll left at the stage speed.
//
// Timelines are generated by `build()` from a repeating cadence so chapters can
// be packed densely (lots of obstacles + memories) while keeping obstacles
// spaced just above one jump's airtime so they stay clearable. Memories are
// interleaved at floating heights between obstacles; low ones are grabbed while
// running, higher ones reward a jump.

export const GROUND_Y = 150; // y of the ground surface (object bottoms rest here)

// Natural resting / approach height per obstacle (object top in 320x180 space).
const OBSTACLE_Y = {
  schoolbag: 132, chair: 130, bookStack: 128,
  paperStack: 134, deadlineClock: 132, questionMarkHigh: 100, questionMarkLow: 134,
  trafficCone: 132, motorbike: 134, deadline: 132,
};
// Rotating heights for memory pickups (mix of run-grab and jump-grab).
const MEM_Y = [105, 92, 100, 86, 96, 108];

// Build a dense timeline: `count` obstacles every `gap` seconds (cycling
// `obstacles`), each preceded by a memory (cycling `memories`). `injects` are
// fixed extra spawns (e.g. power-ups); `endItems` trail after the last obstacle.
function build({ start = 1.0, gap, count, obstacles, memories, injects = [], endItems = [] }) {
  const tl = [];
  for (let i = 0; i < count; i++) {
    const t = +(start + i * gap).toFixed(2);
    const obs = obstacles[i % obstacles.length];
    tl.push({ time: t, id: obs, y: OBSTACLE_Y[obs] ?? 132 });
    if (memories.length) {
      const mem = memories[i % memories.length];
      tl.push({ time: +(t - gap * 0.4).toFixed(2), id: mem, y: MEM_Y[i % MEM_Y.length] });
    }
  }
  for (const inj of injects) tl.push({ ...inj });
  let t = start + count * gap;
  for (const id of endItems) { tl.push({ time: +t.toFixed(2), id, y: 85 }); t += 1.1; }
  return tl.sort((a, b) => a.time - b.time);
}

export const STAGES = [
  {
    id: "classroom",
    title: "Chương 1: Lớp Học",
    subtitle: "Kỷ Niệm Đầu Tiên",
    duration: 16,
    speed: 118, // virtual px / second
    theme: "classroom",
    sky: "#f6d58d",
    timeline: build({
      gap: 0.8, count: 18,
      obstacles: ["schoolbag", "chair", "bookStack"],
      memories: ["notebook", "pen", "ruler", "eraser", "chalk", "redScarf", "apple"],
      endItems: ["loveNote"],
    }),
  },
  {
    id: "paris",
    title: "Chương 2: Paris",
    subtitle: "Học Tập, Xa Cách & Thành Tựu",
    duration: 19,
    speed: 140,
    theme: "paris",
    sky: "#bcd8ff",
    timeline: build({
      gap: 0.72, count: 24,
      // alternating jump (paper/clock) and duck/jump (question marks) hazards
      obstacles: ["paperStack", "questionMarkHigh", "deadlineClock", "questionMarkLow"],
      memories: ["laptopParis", "papers", "croissant", "baguette", "thesisBook", "metroTicket", "professor"],
      endItems: ["committee"],
    }),
  },
  {
    id: "saigon",
    title: "Chương 3: Sài Gòn",
    subtitle: "Trở Về Nhà",
    duration: 19.5,
    speed: 156,
    theme: "saigon",
    sky: "#ffb36b",
    timeline: build({
      gap: 0.8, count: 22,
      obstacles: ["trafficCone", "motorbike", "deadline"],
      memories: ["reports", "laptopSaigon", "pho", "banhMi", "nonLa", "lotus", "smoothie"],
      injects: [
        { time: 3.0, id: "coffee", y: 90 },        // speed boost
        { time: 10.0, id: "grilledChicken", y: 88 }, // restores a heart
      ],
      endItems: ["finalHeart"],
    }),
  },
];
